# Generated by Django 6.0.7 on 2026-07-11 03:23

import samples.models.book
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=samples.models.book.Book.upload_path),
        ),
    ]
